language: php

php:
    - '7.0'
    - '7.1'
    - '7.2'
    - '7.3'

install:
    - composer install

before_script:
    - mkdir -p build/logs

script:
    - composer phpcs
    - composer phpmd
    - composer phpcpd
    - composer test

after_script:
    - php vendor/bin/coveralls -v
